language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get -d -v ./... && go build -v ./...
  - go get github.com/stretchr/testify/assert
  
script:
  - go test ./... 
  - go test ./... -cover