language: go

go:
  - 1.10
  - 1.11
  - 1.12

install:
  - go get -d -v ./... && go build -v ./...
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - curl -s https://codecov.io/bash | bash
